# -*- coding: utf-8 -*-
"""
llm_narrative.py — hybrid commentary via the Claude API
=======================================================
The college lists, probabilities, tiers, and formatting stay 100% deterministic
(scoring.py / assemble.py). ONLY the section prose is generated by Claude, giving
counselor-quality, per-student writing.

Safe by design: if no ANTHROPIC_API_KEY is configured, or the API call fails for
any reason, callers fall back to the built-in template narrative (narrative.py).

Model: claude-opus-4-8 (Anthropic's most capable Opus-tier model).
"""

import json
import os

from report_engine import NAVY, RED, GOLD, GREEN, TEXT

MODEL = "claude-opus-4-8"
ACCENT = {"reach": RED, "match": GOLD, "safety": GREEN, "navy": NAVY}

SCHEMA = {
    "type": "object",
    "properties": {
        "methodology": {"type": "string"},
        "testing_bullets": {"type": "array", "items": {"type": "string"}},
        "core_strategy": {"type": "string"},
        "national_intro": {"type": "string"},
        "instate_intro": {"type": "string"},
        "lac_intro": {"type": "string"},
        "ed_recommendation": {"type": "string"},
        "action_intro": {"type": "string"},
        "steps": {"type": "array", "items": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "bullets": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["title", "bullets"],
            "additionalProperties": False,
        }},
    },
    "required": ["methodology", "testing_bullets", "core_strategy", "national_intro",
                 "instate_intro", "lac_intro", "ed_recommendation", "action_intro", "steps"],
    "additionalProperties": False,
}


def available():
    return bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())


# ---------------------------------------------------------------- prompt
def _facts(profile, lists):
    def names(rows, n):
        return ", ".join("%s (%s, %s)" % (r[0], r[1], r[2]) for r in rows[:n]) or "—"
    nat = lists["national"]
    strong_ed = [r[0] for r in lists["ed"] if r[4].startswith("★★")][:6] \
        or [r[0] for r in lists["ed"] if r[4].startswith("★")][:6]
    gpa = ("UW %.2f" % profile["uw_gpa"]) if profile["uw_gpa"] else \
          (("W %.2f" % profile["w_gpa"]) if profile["w_gpa"] else "N/A")
    return {
        "name": profile["name"], "first": profile["name"].split()[0],
        "home_state": profile["home_state_name"] or "unknown",
        "gpa": gpa, "test": profile["test_display"] if profile["has_test"] else "no test on file",
        "rigor": profile["rigor"], "leadership": profile["leadership"],
        "service": profile["service"], "awards": profile["awards_present"],
        "essays": profile["essays"], "major": profile["major"],
        "strength_index": round(profile["S"]),
        "reach_examples": names(nat["reach"], 6),
        "match_examples": names(nat["match"], 6),
        "safety_examples": names(nat["safety"], 6),
        "instate_examples": names(lists["instate"]["reach"] + lists["instate"]["match"]
                                  + lists["instate"]["safety"], 6),
        "ed_targets": ", ".join(strong_ed) or "—",
        "counts": lists["national_counts"],
    }


def _prompt(profile, lists, lang):
    f = _facts(profile, lists)
    langline = ("Write ALL text in natural, professional Korean (존댓말). Refer to the "
                "student as “%s 학생”. Keep college names, U.S. state names, and abbreviations "
                "(SAT, ACT, ED, EA, GPA, AP, etc.) in English/Latin script." % f["first"]) \
        if lang == "Kor" else "Write ALL text in clear, professional English."
    return (
        "You are a seasoned U.S. college-admissions counselor writing the prose sections of a "
        "strategy report. The college lists, tiers, and admit probabilities are ALREADY COMPUTED "
        "by a separate engine — do NOT invent, restate, or contradict any numbers; write guidance "
        "that is consistent with the profile and the tiers.\n\n"
        "%s\n\n"
        "STUDENT PROFILE\n"
        "- Name: %s (home state: %s)\n"
        "- GPA: %s · Test: %s · Advanced courses: %d · Leadership: %d · Service: ~%d hrs\n"
        "- Awards on file: %s · Essays/recs: %s · Intended major: %s\n"
        "- Internal strength index: %d/100 (higher = stronger applicant)\n"
        "- National pool tiered to Reach %d / Match %d / Safety %d\n"
        "- Example Reach schools: %s\n"
        "- Example Match schools: %s\n"
        "- Example Safety schools: %s\n"
        "- In-state schools: %s\n"
        "- Best Early-Decision targets (already selected): %s\n\n"
        "WRITE JSON with these fields (concise, specific, sober — no fluff, no hype, no invented "
        "statistics):\n"
        "- methodology: 3–5 sentences summarizing the profile and naming the 1–2 highest-leverage "
        "improvements before applications.\n"
        "- testing_bullets: 3–4 short bullets on standardized-test strategy for THIS student "
        "(home-state test policy, submit vs. withhold, whether to raise the score).\n"
        "- core_strategy: 2–3 sentences — the single most important strategic thrust.\n"
        "- national_intro: 1–2 sentences introducing the national list (note it excludes %s and LACs).\n"
        "- instate_intro: 1–2 sentences on the in-state (%s) list and its cost/scholarship value.\n"
        "- lac_intro: 1–2 sentences on the Liberal Arts College list fit.\n"
        "- ed_recommendation: 2–3 sentences naming the best ED targets above and the tradeoff.\n"
        "- action_intro: 1 sentence introducing the 12th-grade action plan.\n"
        "- steps: EXACTLY 4 objects, each {title, bullets:[2–3 short bullets]}, ordered by impact: "
        "(1) the biggest lever, (2) course rigor / grades, (3) essays·activities·service, "
        "(4) recommendations·deadlines·finances. Titles are short imperative phrases.\n"
        % (langline, f["name"], f["home_state"], f["gpa"], f["test"], f["rigor"],
           f["leadership"], f["service"], "yes" if f["awards"] else "none",
           f["essays"], f["major"], f["strength_index"],
           f["counts"]["reach"], f["counts"]["match"], f["counts"]["safety"],
           f["reach_examples"], f["match_examples"], f["safety_examples"],
           f["instate_examples"], f["ed_targets"], f["home_state"], f["home_state"])
    )


# ---------------------------------------------------------------- apply
def _bullets(runs_prefix_color, items):
    out = []
    for j, text in enumerate(items):
        after = 0 if j == len(items) - 1 else 40
        out.append(([("· ", True, runs_prefix_color, 18), (text, False, TEXT, 18)], after))
    return out


def _apply(base, d):
    base["methodology"] = d["methodology"]
    base["national_intro"] = d["national_intro"]
    base["instate_intro"] = d["instate_intro"]
    base["lac_intro"] = d["lac_intro"]
    base["action_intro"] = d["action_intro"]
    base["core"] = [base["core"][0], ([(d["core_strategy"], False, TEXT, 20)], 0)]
    base["ed_rec"] = [base["ed_rec"][0], ([(d["ed_recommendation"], False, TEXT, 18)], 0)]
    if d.get("testing_bullets"):
        base["testing"] = [base["testing"][0]] + _bullets(NAVY, d["testing_bullets"])
    steps = d.get("steps") or []
    if len(steps) == len(base["steps"]):          # only override if shape matches
        new_steps = []
        for i, (tier, _box) in enumerate(base["steps"]):
            accent = ACCENT[tier]
            title = steps[i].get("title", "")
            bl = steps[i].get("bullets", [])
            paras = [([("STEP %d. " % (i + 1), True, accent, 18), (title, True, NAVY, 18)], 60)]
            paras += _bullets(accent, bl)
            new_steps.append((tier, paras))
        base["steps"] = new_steps
    return base


def enhance(profile, lists, base_narr, lang="Eng"):
    """Override the prose fields of `base_narr` with Claude-generated text.
    Raises on any error so the caller can fall back to the template."""
    import anthropic
    client = anthropic.Anthropic()
    # output_config passed via extra_body so this works across SDK versions.
    resp = client.messages.create(
        model=MODEL,
        max_tokens=3000,
        system="Return only valid JSON matching the requested fields. Be concise and specific.",
        messages=[{"role": "user", "content": _prompt(profile, lists, lang)}],
        extra_body={"output_config": {"format": {"type": "json_schema", "schema": SCHEMA}}},
    )
    if getattr(resp, "stop_reason", None) == "refusal":
        raise RuntimeError("model refused")
    text = next(b.text for b in resp.content if b.type == "text")
    return _apply(base_narr, json.loads(text))
